services:
  db:
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: app_dev
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5432:5432"
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379"
    volumes:
      - redis:/var/lib/redis/data
  sidekiq:
    build: .
    depends_on:
      - redis
    command: bundle exec sidekiq
    environment:
      REDIS_URL: redis://redis:6379/0
  web:
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_HOST: db
      DB_NAME: app_dev
      DB_NAME_TEST: app_test
      DB_USERNAME: appuser
      DB_PASSWORD: apppass
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
volumes:
  postgres_data:
  redis: